name: Stocks Products Workflow
run-name: ${{ github.actor }} is testing Stocks Products
on:
  push:
    branches: main
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PG_NAME: ${{ secrets.PG_NAME }}
      PG_HOST: ${{ secrets.PG_HOST }}
      PG_PORT: ${{ secrets.PG_PORT }}
      PG_USER: ${{ secrets.PG_USER }}
      PG_PASSWORD: ${{ secrets.PG_PASSWORD }}
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: ${{ env.PG_NAME }}
          POSTGRES_USER: ${{ env.PG_USER }}
          POSTGRES_PASSWORD: ${{ env.PG_PASSWORD }}
        ports:
          - 5432:5432
        options:
          --health-cmd pg_isready
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Клонируем репозиторий
        uses: actions/checkout@v4
      - name: Установка Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Установка зависимостей
        run: python -m pip install -r requirements.txt
      - name: Линтинг кода
        run: flake8 --exclude migrations --ignore F401,E501
      - name: Миграции
        run: |
          python manage.py makemigrations
          python manage.py migrate
      - name: Наполнение БД фикстурами
        run: python manage.py loaddata stock_products.json
      - name: Тестирование
        run: python manage.py test
  deploy:
    name: Деплой кода на нашем сервере
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Подключаемся к нашему серверу
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: expect ./deploy.exp
